### ISSUE TITLE
Common Sticky Cache Issue: Custom element doesn't exist: service-call.

### ISSUE THREAD

**Issue by pducos** [Nerwyn/custom-card-features#110]
Nerwyn (the developer) here. This is a caching issue caused by a recent update to the name of this repository. @voxmatt did a great write up in this thread [down here](https://github.com/Nerwyn/custom-card-features/issues/110#issuecomment-2833550170) which explains various ways to fix this issue, as the normal clear browser/app cache methods may not work.

---

**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

The card was working fine a few days ago, now the custom features row does not appear. The follwing error shows on the ui "Custom element doesn't exist: service-call."

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Card Config**

features:
  - type: custom:service-call
    entries:
      - type: button
        entity_id: light.patio_switch_center
        icon: mdi:flower
        tap_action:
          action: toggle
          target:
            entity_id: light.patio_switch_center
          data: {}
        styles: |-
          :host { 
             background-color: {% if is_state('light.patio_switch_center', 'on') %} orange {% else %} dark gray {% endif %};
             }
  - type: custom:service-call
    entries:
      - type: button
        entity_id: light.ground_stairs_switch_nook
        icon: mdi:wardrobe
        tap_action:
          action: toggle
          target:
            entity_id: light.ground_stairs_switch_nook
          data: {}
        styles: |-
          :host { 
             background-color: {% if is_state('light.ground_stairs_switch_nook', 'on') %} orange {% else %} dark gray {% endif %};
             }
      - type: button
        entity_id: light.livingroom_switch_dining
        icon: mdi:table-chair
        tap_action:
          action: toggle
          target:
            entity_id: light.livingroom_switch_dining
          data: {}
        styles: |-
          :host { 
             background-color: {% if is_state('light.livingroom_switch_dining', 'on') %} orange {% else %} dark gray {% endif %};
             }
      - type: button
        entity_id: light.livingroom_switch_tv
        icon: mdi:television
        tap_action:
          action: toggle
          target:
            entity_id: light.livingroom_switch_tv
          data: {}
        styles: |-
          :host { 
             background-color: {% if is_state('light.livingroom_switch_tv', 'on') %} orange {% else %} dark gray {% endif %};
             }
type: tile
entity: input_select.floor_select
hide_state: true
name: Ground Floor
grid_options:
  columns: full
icon: mdi:home-floor-g
visibility:
  - condition: and
    conditions:
      - condition: state
        entity: input_boolean.alarm_panel
        state: "off"
      - condition: state
        entity: input_select.floor_select
        state: Ground Floor
tap_action:
  action: none
icon_tap_action:
  action: none
hold_action:
  action: none
features_position: bottom
vertical: false

**Additional information:**

**Comment by Nerwyn** [comment]
This is likely due to a recent update updating the repository and output file names. Try uninstalling this feature from HACS, restarting Home Assistant, and then reinstalling it. If the issue persists make sure that the URL [in frontend resources](http://homeassistant.local:8123/config/lovelace/resources) matches the folder and file name in `config/www/community`.

The updated endpoints should be `custom-card-features/custom-card-features.min.js`, but if they're using the old `service-call-tile-features/custom-features-row.min.js` name and both match it should be okay, as long as they match. You may have issues with external access due to browser/app/external provider caching issue, and would have to clear cache with each of them.

**Comment by pducos** [comment]
I tried reinstalling with a reboot and the problem persists.

Checking the frontend resoruces, both items are there and have the name correctly. However they have a hacstag and number after. Should it have that? Could the tag be incorrect?

/hacsfiles/custom-card-features/custom-card-features.min.js?hacstag=xxxxxxxxxxxx
/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=xxxxxxxxxxxx


Could it also be an issue that I have both the custom card and the service call? Should it only be one of them? could it have some sort of conflict?

P

**Comment by xenofex7** [comment]
same here...
The problem for me only occurs when I access via https, locally via http, the error does not appear. Maybe that helps...

**Comment by Nerwyn** [comment]
> Checking the frontend resoruces, both items are there and have the name correctly.

Only one should be there. Delete the one that doesn't match the folder and file name in `config/www/community`. While it shouldn't cause it not to load it shouldn't be there. Are there any errors in the browser console?

> The problem for me only occurs when I access via https, locally via http, the error does not appear. Maybe that helps...

Definitely a cache issue. Clear browser/companion app/Cloudflare/Nabu Casa/etc cache.

**Comment by radugeo74** [comment]
same problem.
Resolved after deleting in [http://homeassistant.local:8123/config/lovelace/resources](url) the /hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=xxxxxxxxxxxx, and in config/www/community the service call directory, after that i installed the new version named custom card features and made a restart of HA

**Comment by voxmatt** [comment]
I'm having the same issue as @xenofex7 (confirmed that it works locally via http, but not via https; nor does the iOS app work).

I reset local caches, including fully resetting the iOS app, and still doesn't work. I'll try uninstalling from HACS and reinstalling.

Fwiw, this only began occurring after updating to 4.3.9

**Comment by voxmatt** [comment]
Okay, confirmed that this was a cache issue.

If you want to confirm that it is just a cache issue for yourself, I recommend finding the finding the resource URL the dashboard is using for custom-card-features. There are a couple ways to find these, but here's an easy one:

- Go to your dashboard
- click the pencil to enter edit mode
- click the three-dot menu in the upper-right
- select "manage resources"
- find the "custom-card-features" resource url. It will look something like `/hacsfiles/custom-card-features/custom-card-features.min.js?hacstag=698501153439`
- now take that url and try to load it directly `[your-home-assistant-url; e.g. http://homeassistant.local:8123]` + `the above url`
- if that loads in an incognito window, but not your normal window, you have a cache issue


In my situation, it seemed to be a service worker holding onto the cached url. So a regular `cmd-shift-r` did *not* work. This is a bit of "try everything", but it worked:

- load the site you want to fix
- open dev tools (`cmd-shift-i` on mac)
- open the "application" tab
- select "storage" on the left
- click "clear site data" button
- then select "service workers" on the left (still in the application tab)
- check "Offline" 
- reload the page
- deselect "Offline"
- reload page (`cmd-shift-r` for good measure)

On the iOS app you have to do the following:

- Settings → Companion App
- Debugging
- "Reset frontend cache"
- Force quit application, and reopn

I hope this helps!

**Comment by xenofex7** [comment]
From my side, the issue has been resolved, either due to the update to version 4.3.9 or because of the reinstallation. It’s working again now - both http and https

**Comment by AlexKusnezov** [comment]
for me nothing works past 4.3.4. Had to revert to it.
